package com.example.energymanagementapp.ui.localization

data class AppStrings(
    // Ekranų tituliniai užrašai
    val welcome: String,
    val letsManageYourDay: String,
    val energyManager: String,
    val setBreaks: String,
    val chooseActivities: String,
    val setBreakDuration: String,
    val breakTime: String,
    val daySummary: String,
    val setEnergy: String,
    val manageActivitiesTitle: String,
    val yourProgress: String,
    val createPlan: String,
    val yourPlan: String,

    // Mygtukų užrašai
    val startPlan: String,
    val continuePlan: String,
    val viewTodayPlan: String,
    val viewSummary: String,
    val pastDays: String,
    val manageActivities: String,
    val backToPlan: String,
    val confirm: String,
    val continueText: String,
    val cancel: String,
    val updateBreak: String,
    val confirmBreak: String,
    val removeBreak: String,
    val skip: String,
    val goHome: String,
    val goBack: String,
    val setTime: String,
    val addActivity: String,
    val delete: String,
    val backToHome: String,
    val energyAndTime: String,
    val setEnergyAndEndTime: String,
    val activities: String,
    val breaks: String,
    val breaksOptional: String,
    val breaksOptionalShort: String,
    val confirmPlan: String,
    val cancelPlan: String,
    val confirmCompleted: String,

    // Turinio tekstas
    val tooLateToStartToday: String,
    val comeBackTomorrowMorning: String,
    val cancelPlanToManageActivities: String,
    val finishPlanToManageActivities: String,
    val dayCompleted: String,
    val assignBreaksToActivities: String,
    val breakLabel: String,
    val noBreakSet: String,
    val pickWhatYouWantToDoToday: String,
    val weather: String,
    val now: String,
    val inThreeHours: String,
    val evening: String,
    val unusedEnergy: String,
    val youStillHaveEnergyLeft: (Int) -> String,
    val energy: String,
    val spoons: String,
    val optionalHelpsWithRecovery: String,
    val relaxAndRecover: String,
    val howYourDayWent: String,
    val energyUsed: String,
    val totalRestTime: String,
    val completed: String,
    val notCompleted: String,
    val completedAt: (String) -> String,
    val howMuchEnergyToday: String,
    val endsAt: (String) -> String,
    val chooseFutureTime: String,
    val createNewActivitiesOrDeleteExistingOnes: String,
    val newActivity: String,
    val activityName: String,
    val energyCost: String,
    val yourActivities: String,
    val trackYourPastDays: String,
    val completedStatus: String,
    val partiallyCompleted: String,
    val notCompletedStatus: String,
    val setEnergyChooseActivitiesAndStartYourDay: String,
    val selectedActivities: String,
    val planEndsAt: (String) -> String,
    val todaysWeather: String,
    val loadingTodaysWeather: String,
    val bestOfLuckCompletingTasks: String,
    val toDo: String,
    val onceCompleteCannotCancel: String,
    val energyLeft: String,
    val clearSky: String,
    val mainlyClear: String,
    val partlyCloudy: String,
    val cloudy: String,
    val fog: String,
    val drizzle: String,
    val rain: String,
    val snow: String,
    val rainShowers: String,
    val thunderstorm: String,
    val unknownWeather: String,

    // Aprašymai
    val toggleAccessibilityMode: String
)